cd ~/workspace/tp-2018-2c-RogerThat/S-AFA
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/tp-2018-2c-RogerThat/FuncionesConexiones/Debug
cd ~/workspace/tp-2018-2c-RogerThat/DAM
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/tp-2018-2c-RogerThat/FuncionesConexiones/Debug
cd ~/workspace/tp-2018-2c-RogerThat/CPU
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/tp-2018-2c-RogerThat/FuncionesConexiones/Debug
cd ~/workspace/tp-2018-2c-RogerThat/FM9
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/tp-2018-2c-RogerThat/FuncionesConexiones/Debug
cd ~/workspace/tp-2018-2c-RogerThat/MDJ
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/tp-2018-2c-RogerThat/FuncionesConexiones/Debug
cd ~/workspace/tp-2018-2c-RogerThat